#!/bin/bash -l
    GIT_REPO=$HOME/repos/yuxiang.ren.git
    TMP_GIT_CLONE=$HOME/tmp/git/renyuxiang.ren
    PUBLIC_WWW=/var/www/yuxiang.ren
    rm -rf ${TMP_GIT_CLONE}
    git clone $GIT_REPO $TMP_GIT_CLONE
    rm -rf ${PUBLIC_WWW}/*
    cp -rf ${TMP_GIT_CLONE}/* ${PUBLIC_WWW}
    cd ~
    exit